import os
import re

from dotenv import load_dotenv
from pydantic_settings import BaseSettings

load_dotenv()

DEFAULT_DB_HOST = "192.168.25.203"
DEFAULT_DB_PORT = "5432"
DEFAULT_DB_NAME = "precos-farmacia"
DEFAULT_DB_USER = "admin"
DEFAULT_DB_PASSWORD = "password"
DEFAULT_PORT = 8001
DEFAULT_CEP = ""
DEFAULT_SEARCH_TERMS = "dipirona,paracetamol,ibuprofeno"
DEFAULT_SCHEDULED_COLLECTION_MAX_ITEMS_PER_CEP = 50
DEFAULT_SCHEDULED_COLLECTION_SLOTS = "08:00,15:00"
DEFAULT_SCHEDULED_COLLECTION_SLOT_WINDOW_MINUTES = 120
DEFAULT_PRICE_RETENTION_DAYS = 90
DEFAULT_REFERENCE_DATA_DIR = "data/reference"
DEFAULT_UVICORN_ACCESS_LOG = True
DEFAULT_LOG_OPERATION_JOB_REUSED = False
DEFAULT_EMBED_OPERATION_WORKER = True
DEFAULT_EMBED_OPERATION_WORKER_POLL_SECONDS = 5
DEFAULT_SCRAPER_TERM_BATCH_SIZE = 5
DEFAULT_INTERNAL_API_AUTH_ENABLED = False
DEFAULT_INTERNAL_API_TOKEN = ""


def _env_str(name: str, default: str) -> str:
    return os.getenv(name, default)


def _env_int(name: str, default: int) -> int:
    return int(os.getenv(name, str(default)))


def _env_bool(name: str, default: bool = False) -> bool:
    default_value = "true" if default else "false"
    return os.getenv(name, default_value).lower() == "true"


def _optional_normalized_cep(value: str | None) -> str | None:
    normalized = re.sub(r"\D", "", value or "")
    return normalized if len(normalized) == 8 else None


class Settings(BaseSettings):
    POSTGRES_USER: str = _env_str("POSTGRES_USER", DEFAULT_DB_USER)
    POSTGRES_PASSWORD: str = _env_str("POSTGRES_PASSWORD", DEFAULT_DB_PASSWORD)
    DB_HOST: str = _env_str("DB_HOST", DEFAULT_DB_HOST)
    DB_PORT: str = _env_str("DB_PORT", DEFAULT_DB_PORT)
    POSTGRES_DB: str = _env_str("POSTGRES_DB", DEFAULT_DB_NAME)
    PORT: int = _env_int("PORT", DEFAULT_PORT)

    CEP: str = _env_str("CEP", DEFAULT_CEP)

    PANVEL_SEARCH_TERMS: str = _env_str("PANVEL_SEARCH_TERMS", DEFAULT_SEARCH_TERMS)
    FARMASESI_SEARCH_TERMS: str = _env_str("FARMASESI_SEARCH_TERMS", DEFAULT_SEARCH_TERMS)
    SAO_JOAO_SEARCH_TERMS: str = _env_str("SAO_JOAO_SEARCH_TERMS", DEFAULT_SEARCH_TERMS)
    FARMACIA_JARAGUA_SEARCH_TERMS: str = _env_str("FARMACIA_JARAGUA_SEARCH_TERMS", DEFAULT_SEARCH_TERMS)
    DROGASIL_SEARCH_TERMS: str = _env_str("DROGASIL_SEARCH_TERMS", DEFAULT_SEARCH_TERMS)
    CATARINENSE_SEARCH_TERMS: str = _env_str("CATARINENSE_SEARCH_TERMS", DEFAULT_SEARCH_TERMS)
    PRECO_POPULAR_SEARCH_TERMS: str = _env_str("PRECO_POPULAR_SEARCH_TERMS", DEFAULT_SEARCH_TERMS)
    DROGA_RAIA_SEARCH_TERMS: str = _env_str("DROGA_RAIA_SEARCH_TERMS", DEFAULT_SEARCH_TERMS)
    DROGARIA_SAO_PAULO_SEARCH_TERMS: str = _env_str("DROGARIA_SAO_PAULO_SEARCH_TERMS", DEFAULT_SEARCH_TERMS)

    ON_DEMAND_ENABLE_BROWSER_SCRAPERS: bool = _env_bool("ON_DEMAND_ENABLE_BROWSER_SCRAPERS")
    SCHEDULED_COLLECTION_ENABLE_BROWSER_SCRAPERS: bool = _env_bool("SCHEDULED_COLLECTION_ENABLE_BROWSER_SCRAPERS")
    SCHEDULED_COLLECTION_MAX_ITEMS_PER_CEP: int = _env_int(
        "SCHEDULED_COLLECTION_MAX_ITEMS_PER_CEP",
        DEFAULT_SCHEDULED_COLLECTION_MAX_ITEMS_PER_CEP,
    )
    SCHEDULED_COLLECTION_SLOTS: str = _env_str("SCHEDULED_COLLECTION_SLOTS", DEFAULT_SCHEDULED_COLLECTION_SLOTS)
    SCHEDULED_COLLECTION_SLOT_WINDOW_MINUTES: int = _env_int(
        "SCHEDULED_COLLECTION_SLOT_WINDOW_MINUTES",
        DEFAULT_SCHEDULED_COLLECTION_SLOT_WINDOW_MINUTES,
    )
    PRICE_RETENTION_DAYS: int = _env_int("PRICE_RETENTION_DAYS", DEFAULT_PRICE_RETENTION_DAYS)
    MCP_EXPOSE_ADMIN_TOOLS: bool = _env_bool("MCP_EXPOSE_ADMIN_TOOLS")
    REFERENCE_DATA_DIR: str = _env_str("REFERENCE_DATA_DIR", DEFAULT_REFERENCE_DATA_DIR)
    UVICORN_ACCESS_LOG: bool = _env_bool("UVICORN_ACCESS_LOG", DEFAULT_UVICORN_ACCESS_LOG)
    LOG_OPERATION_JOB_REUSED: bool = _env_bool("LOG_OPERATION_JOB_REUSED", DEFAULT_LOG_OPERATION_JOB_REUSED)
    EMBED_OPERATION_WORKER: bool = _env_bool("EMBED_OPERATION_WORKER", DEFAULT_EMBED_OPERATION_WORKER)
    EMBED_OPERATION_WORKER_POLL_SECONDS: int = _env_int(
        "EMBED_OPERATION_WORKER_POLL_SECONDS",
        DEFAULT_EMBED_OPERATION_WORKER_POLL_SECONDS,
    )
    SCRAPER_TERM_BATCH_SIZE: int = _env_int("SCRAPER_TERM_BATCH_SIZE", DEFAULT_SCRAPER_TERM_BATCH_SIZE)
    INTERNAL_API_AUTH_ENABLED: bool = _env_bool("INTERNAL_API_AUTH_ENABLED", DEFAULT_INTERNAL_API_AUTH_ENABLED)
    INTERNAL_API_TOKEN: str = _env_str("INTERNAL_API_TOKEN", DEFAULT_INTERNAL_API_TOKEN)

    @property
    def DATABASE_URL(self) -> str:
        return f"postgresql://{self.POSTGRES_USER}:{self.POSTGRES_PASSWORD}@{self.DB_HOST}:{self.DB_PORT}/{self.POSTGRES_DB}"

    @property
    def DEFAULT_RUNTIME_CEP(self) -> str | None:
        return _optional_normalized_cep(self.CEP)


settings = Settings()
